In [77]:
#!pip install pandas
#!pip install elasticsearch # elasticsearch==8.11.0 si pb de version 

In [42]:
from elasticsearch import Elasticsearch, helpers
import json 
bulk = helpers.bulk # Insertion de masse 

es = Elasticsearch("http://elasticsearch:9200")  # connexion au server es depuis Jupyter 

In [43]:
docs = [
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "To be, or not to be: that is the question."
    },
    {
        "play_name": "Macbeth",
        "speaker": "LADY MACBETH",
        "text_entry": "Out, damned spot! out, I say!"
    },
    {
        "play_name": "Othello",
        "speaker": "OTHELLO",
        "text_entry": "She loved me for the dangers I had passed."
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "Being or not being"
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "I am and I will be"
    },
    {
        "play_name": "Macbeth",
        "speaker": "MACBETH",
        "text_entry": "To be king is everything"
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "To be, or not to be: that is the question."
    },
    {
        "play_name": "Macbeth",
        "speaker": "LADY MACBETH",
        "text_entry": "Out, damned spot! out, I say!"
    },
    {
        "play_name": "Othello",
        "speaker": "OTHELLO",
        "text_entry": "She loved me for the dangers I had passed."
    },
    {
        "play_name": "Macbeth",
        "speaker": "MACBETH",
        "text_entry": "Tomorrow, and tomorrow, and tomorrow.",
        "year": 1606
    },
    {
        "play_name": "King Lear",
        "speaker": "KING LEAR",
        "text_entry": "Blow, winds, and crack your cheeks!",
        "year": 1605
    },
    {
        "play_name": "Julius Caesar",
        "speaker": "MARK ANTONY",
        "text_entry": "Friends, Romans, countrymen, lend me your ears.",
        "year": 1599
    },
    {
        "play_name": "Romeo and Juliet",
        "speaker": "ROMEO",
        "text_entry": "It is the east, and Juliet is the sun.",
        "year": 1595
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "The time is out of joint.",
        "year": 1601
    },
    {
        "play_name": "Othello",
        "speaker": "IAGO",
        "text_entry": "I am not what I am.",
        "year": 1604
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "To be or not to be",
        "year": 1603
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "The time is out of joint",
        "year": 1601
    },
    {
        "play_name": "Othello",
        "speaker": "OTHELLO",
        "text_entry": "She loved me for the dangers I had passed",
        "year": 1604
    },
    {
        "play_name": "Othello",
        "speaker": "IAGO",
        "text_entry": "I am not what I am",
        "year": 1604
    },
    {
        "play_name": "Macbeth",
        "speaker": "MACBETH",
        "text_entry": "Tomorrow and tomorrow and tomorrow",
        "year": 1606
    },
    {
        "play_name": "Macbeth",
        "speaker": "LADY MACBETH",
        "text_entry": "Out damned spot",
        "year": 1606
    },
    {
        "play_name": "King Lear",
        "speaker": "KING LEAR",
        "text_entry": "Blow winds and crack your cheeks",
        "year": 1605
    },
    {
        "play_name": "Romeo and Juliet",
        "speaker": "ROMEO",
        "text_entry": "Juliet is the sun",
        "year": 1595
    },
    {
        "play_name": "Hamlet",
        "speaker": "HAMLET",
        "text_entry": "Love makes us weak",
        "year": 1603
    },
    {
        "play_name": "Othello",
        "speaker": "OTHELLO",
        "text_entry": "I know this love is true",
        "year": 1604
    },
    {
        "play_name": "Macbeth",
        "speaker": "MACBETH",
        "text_entry": "Tomorrow and tomorrow",
        "year": 1606
    },
    {
        "play_name": "Romeo and Juliet",
        "speaker": "ROMEO",
        "text_entry": "Juliet is the sun",
        "year": 1595
    }
]

In [44]:
# ingestion des données 
actions = [
    {
        "_index": "shakespeare", # index == db 
        "_source": doc
    }
    for doc in docs
]

if es.indices.exists(index="shakespeare"):
    es.indices.delete(index="shakespeare")
else:
    es.indices.create(index="shakespeare")

success, errors = bulk(es, actions, refresh=True)

print("Documents indexés :", success)
print("Erreurs :", errors)

Documents indexés : 27
Erreurs : []


In [78]:
res = es.search(
     index="shakespeare",
     query={"match_all": {}}
)

# json.dumps permet d'indenter le code correction
# print( json.dumps(res["hits"]["hits"], indent=2) )

In [35]:
# création d'un autre index
docs = [
{
  "play_name": "Hamlet",
  "speaker": "HAMLET",
  "text_entry": "To be, or not to be: that is the question."
},
{
  "play_name": "Macbeth",
  "speaker": "LADY MACBETH",
  "text_entry": "Out, damned spot! out, I say!"
},
{
  "play_name": "Othello",
  "speaker": "OTHELLO",
  "text_entry": "She loved me for the dangers I had passed."
}
]

actions = [
    {
        "_index": "shakespeare_v2",
        "_source": doc
    }
    for doc in docs
]

if es.indices.exists(index="shakespeare_v2"):
    es.indices.delete(index="shakespeare_v2")
else:
    es.indices.create(index="shakespeare_v2")

success, errors = bulk(es, actions, refresh=True)

print("Documents indexés :", success)
print("Erreurs :", errors)

Documents indexés : 3
Erreurs : []


In [37]:
res = es.search(
     index="shakespeare_v2",
     query={"match_all": {}}
)

data = res["hits"]["hits"] 

In [53]:
import pandas as pd 

dataClean = [ d["_source"] for d in data ]
dataClean

df = pd.DataFrame(dataClean)

In [54]:
df

,play_name,speaker,text_entry
0,Hamlet,HAMLET,"To be, or not to be: that is the question."
1,Macbeth,LADY MACBETH,"Out, damned spot! out, I say!"
2,Othello,OTHELLO,She loved me for the dangers I had passed.


In [60]:
res = es.search(
     index="shakespeare",
     query={"match": {"text_entry" : "be" }}  # recherche par token
)

# res["hits"]["hits"] 

In [79]:
# une recheche range requete structurée pas de full-text → pas de score pertinent, tout est à 1 
query_range = {
    "query": {
        "range": {
            "year": {
                "gte": 1603,
                "lte": 1606
            }
        }
    }
}

res = es.search(index="shakespeare", body=query_range)

#for hit in res["hits"]["hits"]:
#    print(hit["_score"], hit["_source"])

In [80]:
# requete imbriquée 

"""
pas de score pour cette partie de la requête 
{"term": {"play_name.keyword": "Hamlet"}}
{"range": {"year": {"gte": 1601}}}


ici Elasticsearch calcule un score 
{"match": {"text_entry": "love"}}
{"match": {"text_entry": "time"}}

"""

query = {
    "query": {
        "bool": {
            "must": [
                {"term": {"play_name.keyword": "Hamlet"}},
                {"range": {"year": {"gte": 1601}}},
                {
                    "bool": {
                        "should": [
                            {"match": {"text_entry": "love"}},
                            {"match": {"text_entry": "time"}}
                        ],
                        "minimum_should_match": 1
                    }
                }
            ]
        }
    }
}

"""
(play_name = Hamlet) AND (year >= 1601) AND (match love OU match time) 
"""

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_score"], hit["_source"])

5.0109615 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Love makes us weak', 'year': 1603}
4.632104 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint.', 'year': 1601}
4.632104 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint', 'year': 1601}


In [105]:

if False:
    doc = {
      "speaker": "HAMLET",
      "play_name": "Hamlet",
      "year": 1605,
      "text_entry": "love is everywhere"
    }
    res = es.index(
        index="shakespeare",
        document=doc
    )
    
    print(res)


"""
- filtre = A AND B
- score = amélioré si C ou D match avec "minimum_should_match": 0

ce document sort par exemple

{
  "speaker": "HAMLET",
  "play_name": "Hamlet",
  "year": 1605,
  "text_entry": "love is everywhere"
}

"""

query = {
    "query": {
        "bool": {
            "must": [
                {"term": {"play_name.keyword": "Hamlet"}},
                {
                    "range": {
                        "year": {
                            "gte": 1601
                        }
                    }
                }
            ],
            "should": [
                {"match": {"text_entry": "love"}},
                {"match": {"text_entry": "time"}}
            ],
            "minimum_should_match": 0
        }
    }
}

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_score"], hit["_source"])

4.762534 {'speaker': 'HAMLET', 'play_name': 'Hamlet', 'year': 1605, 'text_entry': 'love is everywhere'}
4.5508695 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Love makes us weak', 'year': 1603}
4.2132573 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint.', 'year': 1601}
4.2132573 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint', 'year': 1601}
3.955952 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Time is out of joint, O cursed spite!', 'year': 1602}
2.049822 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be or not to be', 'year': 1603}


La différence concrète entre `0` et `1` apparaît ici :

* avec `minimum_should_match: 0`, on voit aussi :

```python
2.049822 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be or not to be', 'year': 1603}
```

* avec `minimum_should_match: 1`, cette ligne disparaît.

## Ce que cela prouve

Ce document :

```json
{
  "play_name": "Hamlet",
  "speaker": "HAMLET",
  "text_entry": "To be or not to be",
  "year": 1603
}
```

respecte bien :

* `play_name = Hamlet`
* `year >= 1601`

mais il ne matche ni :

* `"love"`
* ni `"time"`

Donc :

### Avec `minimum_should_match = 0`

il est accepté, parce que les `should` sont optionnels.

### Avec `minimum_should_match = 1`

il est rejeté, parce qu’il faut au moins un match sur `love` ou `time`.

### Cas `0`

```text
(A AND B) + bonus éventuel si C ou D
```

### Cas `1`

```text
(A AND B) AND (C OR D)
```

## Pourquoi le reste de la liste ne change presque pas

Parce que les autres documents affichés contiennent déjà `love` ou `time`, donc ils satisfont aussi bien :

* la version souple (`0`)
* que la version stricte (`1`)

Leur score reste donc du même ordre, et ils restent dans les résultats.

```text
minimum_should_match = 0
→ les clauses should restent optionnelles

minimum_should_match = 1
→ au moins une clause should doit matcher
```


```text
ce document sort par exemple
{
  "speaker": "HAMLET",
  "play_name": "Hamlet",
  "year": 1605,
  "text_entry": "love is everywhere"
}
```

Oui, mais ce document sort dans les deux cas, puisque lui matche déjà `"love"`.

Le document le plus intéressant pour montrer la différence est justement :

```json
{
  "play_name": "Hamlet",
  "speaker": "HAMLET",
  "text_entry": "To be or not to be",
  "year": 1603
}
```

```python
print("Avec minimum_should_match = 0 : le doc 'To be or not to be' apparaît")
print("Avec minimum_should_match = 1 : il disparaît")
```

In [99]:
# Et cette histoire de token 
response = es.indices.analyze(
    body={
        "analyzer": "standard",
        "text": "The time is out of joint."
    }
)

for token in response["tokens"]:
    print(token["token"])

the
time
is
out
of
joint


In [106]:
query = {
    "query": {
        "match" : { "text_entry" : "the" }
    }
}

# res = es.search(index="shakespeare", body=query)
# res["hits"]["hits"]

### Trouver toutes les phrases de Hamlet

In [108]:
query = {
    "query": {
        "term": {
            "play_name.keyword": "Hamlet"
        }
    }
}

res = es.search(index="shakespeare", body=query)

#for hit in res["hits"]["hits"]:
#    print(hit["_source"])

{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Being or not being'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'I am and I will be'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint.', 'year': 1601}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be or not to be', 'year': 1603}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'The time is out of joint', 'year': 1601}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Love makes us weak', 'year': 1603}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Time is out of joint, O cursed spite!', 'year': 1602}
{'speaker': 'HAMLET', 'play_name': 'Hamlet', 'year': 1605, 'text_entry': 'love is everywhere'}


### Trouver les phrases contenant "love"

In [109]:
query = {
    "query": {
        "match": {
            "text_entry": "love"
        }
    }
}

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_source"])

{'speaker': 'HAMLET', 'play_name': 'Hamlet', 'year': 1605, 'text_entry': 'love is everywhere'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Love makes us weak', 'year': 1603}
{'play_name': 'Othello', 'speaker': 'OTHELLO', 'text_entry': 'I know this love is true', 'year': 1604}


### Trouver les phrases contenant "love" prononcées par Othello

In [110]:
query = {
    "query": {
        "bool": {
            "must": [
                {"match": {"text_entry": "love"}},
                {"term": {"speaker.keyword": "OTHELLO"}}
            ]
        }
    }
}

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_source"])

{'play_name': 'Othello', 'speaker': 'OTHELLO', 'text_entry': 'I know this love is true', 'year': 1604}


### Trouver toutes les phrases sauf celles de Macbeth

In [111]:
query = {
    "query": {
        "bool": {
            "must_not": [
                {"term": {"play_name.keyword": "Macbeth"}}
            ]
        }
    }
}

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_source"])

{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
{'play_name': 'Othello', 'speaker': 'OTHELLO', 'text_entry': 'She loved me for the dangers I had passed.'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'Being or not being'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'I am and I will be'}
{'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
{'play_name': 'Othello', 'speaker': 'OTHELLO', 'text_entry': 'She loved me for the dangers I had passed.'}
{'play_name': 'King Lear', 'speaker': 'KING LEAR', 'text_entry': 'Blow, winds, and crack your cheeks!', 'year': 1605}
{'play_name': 'Julius Caesar', 'speaker': 'MARK ANTONY', 'text_entry': 'Friends, Romans, countrymen, lend me your ears.', 'year': 1599}
{'play_name': 'Romeo and Juliet', 'speaker': 'ROMEO', 'text_entry': 'It is the east, and Juliet is the sun.', 'year': 1595}
{'play_name': 'Hamlet', 'speaker': '

### Trouver les phrases contenant "be" et prononcées par Hamlet ou Othello

In [121]:
# filter sera sans impact sur le score 
query = {
    "query": {
        "bool": {
            "must": [
                {"match": {"text_entry": "be"}}
            ],
            "filter": [
                {
                    "terms": {
                        "speaker.keyword": ["HAMLET", "OTHELLO"]
                    }
                }
            ]
        }
    }
}

res = es.search(index="shakespeare", body=query)

for hit in res["hits"]["hits"]:
    print(hit["_score"], hit["_source"])

2.3437905 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be or not to be', 'year': 1603}
1.9775403 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
1.9775403 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
1.7082942 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'I am and I will be'}


In [120]:
# should aura un impact sur le score 

res = es.search(index="shakespeare", body={
  "query": {
    "bool": {
      "must": [
                {"match": {"text_entry": "be"}},
            ],
      "should": [
        { "term": { "speaker.keyword": "HAMLET" } },
        { "term": { "speaker.keyword": "OTHELLO" } }
      ],
      "minimum_should_match": 1
    }
  }
})

for hit in res["hits"]["hits"]:
    print(hit["_score"], hit["_source"])

3.3936126 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be or not to be', 'year': 1603}
3.0273623 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
3.0273623 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'To be, or not to be: that is the question.'}
2.7581162 {'play_name': 'Hamlet', 'speaker': 'HAMLET', 'text_entry': 'I am and I will be'}
